<?php
class mymoduleActions extends sfActions
{
  public function executeIndex()
  {
    // ...
  }

  public function executeNiak()
  {
    // ...
  }

  public function executeNiek()
  {
    // ...
  }

  public function executeNiik()
  {
    // ...
  }

  public function executeNiok()
  {
    // ...
  }

  public function executeNiuk()
  {
    // ...
  }

  public function executeMiak()
  {
    // ...
  }

  public function executeMiek()
  {
    // ...
  }

  public function executeMiik()
  {
    // ...
  }

  public function executeMiok()
  {
    // ...
  }

  public function executeMiuk()
  {
    // ...
  }
}