<?php
class mymoduleActions extends sfActions
{
  public function executeIndex(sfWebRequest $request)
  {
    // ...
  }

  public function executeA(sfWebRequest $request)
  {
    // ...
  }

  public function executeB(sfWebRequest $request)
  {
    // ...
  }

  public function executeC(sfWebRequest $request)
  {
    // ...
  }

  public function executeD(sfWebRequest $request)
  {
    // ...
  }

  public function executeE(sfWebRequest $request)
  {
    // ...
  }

  public function executeF(sfWebRequest $request)
  {
    // ...
  }

  public function executeG(sfWebRequest $request)
  {
    // ...
  }

  public function executeH(sfWebRequest $request)
  {
    // ...
  }

  public function executeI(sfWebRequest $request)
  {
    // ...
  }

  public function executeJ(sfWebRequest $request)
  {
    // ...
  }

  public function executeK(sfWebRequest $request)
  {
    // ...
  }

  public function executeL(sfWebRequest $request)
  {
    // ...
  }

  public function executeM(sfWebRequest $request)
  {
    // ...
  }

  public function executeN(sfWebRequest $request)
  {
    // ...
  }

  public function executeO(sfWebRequest $request)
  {
    // ...
  }
  public function executeP(sfWebRequest $request)
  {
    // ...
  }

  public function executeQ(sfWebRequest $request)
  {
    // ...
  }

  public function executeR(sfWebRequest $request)
  {
    // ...
  }

  public function executeS(sfWebRequest $request)
  {
    // ...
  }

  public function executeT(sfWebRequest $request)
  {
    // ...
  }
}