<?php
class mymoduleActions extends sfActions
{
  public function executeIndex(sfWebRequest $request)
  {
    // ...
  }

  public function executeA(sfWebRequest $request)
  {
    // ...
  }

  public function executeB(sfWebRequest $request)
  {
    // ...
  }

  public function executeC(sfWebRequest $request)
  {
    // ...
  }

  public function executeD(sfWebRequest $request)
  {
    // ...
  }

  public function executeE(sfWebRequest $request)
  {
    // ...
  }

  public function executeF(sfWebRequest $request)
  {
    // ...
  }

  public function executeG(sfWebRequest $request)
  {
    // ...
  }

  public function executeH(sfWebRequest $request)
  {
    // ...
  }

  public function executeI(sfWebRequest $request)
  {
    // ...
  }

  public function executeJ(sfWebRequest $request)
  {
    // ...
  }
}