<?php
class mymoduleActions extends sfActions
{
  public function executeIndex(sfWebRequest $request)
  {
    // ...
  }

  public function A()
  {
    // ...
  }

  public function B()
  {
    // ...
  }

  public function C()
  {
    // ...
  }

  public function D()
  {
    // ...
  }

  public function E()
  {
    // ...
  }

  public function F()
  {
    // ...
  }

  public function G()
  {
    // ...
  }

  public function H()
  {
    // ...
  }

  public function I()
  {
    // ...
  }

  public function J()
  {
    // ...
  }
}