<?php
// substr not allowed. Must be mb_substr()
strlen('titi');
echo 'strlen';

strlen ('er');
strlen ( 'er' );
strlen  ('er');
strlen    ('er');
strlen
('er');

strlen
  ('er');

mail();
strpos();
strrpos();
substr();
strtolower();
strtoupper();
stripos();
strripos();
strstr();
stristr();
strrchr();
substr_count();
ereg();
eregi();
ereg_replace();
eregi_replace();
split();


// Good usages
mb_send_mail();
mb_strlen();
mb_strpos();
mb_strrpos();
mb_substr();
mb_strtolower();
mb_strtoupper();
mb_stripos();
mb_strripos();
mb_strstr();
mb_stristr();
mb_strrchr();
mb_substr_count();
mb_ereg();
mb_eregi();
mb_ereg_replace();
mb_eregi_replace();
mb_split();